<p style="background:url(https://maf.pagosonline.net/ws/fp?id=$[deviceSessionId]$[usuarioId])"></p>
<img src="https://maf.pagosonline.net/ws/fp/clear.png?id=$[deviceSessionId]$[usuarioId]" />
<script src="https://maf.pagosonline.net/ws/fp/check.js?id=$[deviceSessionId]$[usuarioId]"></script>
<object
	type="application/x-shockwave-flash"
	data="https://maf.pagosonline.net/ws/fp/fp.swf?id=$[deviceSessionId]$[usuarioId]" width="1" height="1"
	id="thm_fp"
>
	<param name="movie" value="https://maf.pagosonline.net/ws/fp/fp.swf?id=$[deviceSessionId]$[usuarioId]" />
</object>